### PR TITLE
Added CascadiaCSS

### PR DESCRIPTION
**Pull request by KatieK2**
I'm happy to re-arrange the list if this isn't to your liking. 😁

### CODE REVIEW

**Comment by benschwarz** [comment]
👍LGTM

**Comment by lukaszklis** [comment]
@benschwarz shall we still merge this PR? :)

**Comment by benschwarz** [comment]
@lukaszklis Yeah… I think I was going to let an 'owner' merge it rather than me reviewing and merging. 🤦‍♂️

**Comment by lukaszklis** [comment]
@KatieK2 based on the message shown on the site, do we still want to add it here?

**Comment by KatieK2** [comment]
I still would love for CascadiaCSS to be part of the CSS Conf org, but I agree that it doesn't make sense right now. Feel free to close this PR - I can do it again when Cascadia gets back up and running. Thanks!

**Comment by lukaszklis** [comment]
@KatieK2 thanks for clarifying this and sorry for quite a delay on reacting on this PR. :D

**Pull request closed without merging**
